// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Meet struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	City       string      `json:"city"`
	Country    string      `json:"country"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	CourseType string      `json:"course_type"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type StandardTime struct {
	ID         uuid.UUID `json:"id"`
	StandardID uuid.UUID `json:"standard_id"`
	Event      string    `json:"event"`
	AgeGroup   string    `json:"age_group"`
	TimeMs     int32     `json:"time_ms"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Swimmer struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	BirthDate        pgtype.Date    `json:"birth_date"`
	Gender           string         `json:"gender"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ThresholdPercent pgtype.Numeric `json:"threshold_percent"`
}

type Time struct {
	ID        uuid.UUID   `json:"id"`
	SwimmerID uuid.UUID   `json:"swimmer_id"`
	MeetID    uuid.UUID   `json:"meet_id"`
	Event     string      `json:"event"`
	TimeMs    int32       `json:"time_ms"`
	EventDate pgtype.Date `json:"event_date"`
	Notes     pgtype.Text `json:"notes"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type TimeStandard struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CourseType  string      `json:"course_type"`
	Gender      string      `json:"gender"`
	IsPreloaded bool        `json:"is_preloaded"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
