// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountMeets(ctx context.Context, dollar_1 string) (int64, error)
	CountSwimmers(ctx context.Context) (int64, error)
	CountTimes(ctx context.Context, arg CountTimesParams) (int64, error)
	// Returns count of times per event for a swimmer
	CountTimesByEvent(ctx context.Context, arg CountTimesByEventParams) ([]CountTimesByEventRow, error)
	CreateMeet(ctx context.Context, arg CreateMeetParams) (Meet, error)
	CreateStandard(ctx context.Context, arg CreateStandardParams) (TimeStandard, error)
	CreateStandardTime(ctx context.Context, arg CreateStandardTimeParams) (StandardTime, error)
	CreateSwimmer(ctx context.Context, arg CreateSwimmerParams) (Swimmer, error)
	CreateTime(ctx context.Context, arg CreateTimeParams) (Time, error)
	DeleteMeet(ctx context.Context, id uuid.UUID) error
	DeleteStandard(ctx context.Context, id uuid.UUID) error
	DeleteStandardTime(ctx context.Context, id uuid.UUID) error
	DeleteStandardTimesByStandardID(ctx context.Context, standardID uuid.UUID) error
	DeleteSwimmer(ctx context.Context, id uuid.UUID) error
	DeleteTime(ctx context.Context, id uuid.UUID) error
	DeleteTimesByMeet(ctx context.Context, meetID uuid.UUID) error
	// Check if an event already exists for a specific meet and swimmer
	EventExistsForMeet(ctx context.Context, arg EventExistsForMeetParams) (bool, error)
	GetMeet(ctx context.Context, id uuid.UUID) (Meet, error)
	GetMeetWithTimeCount(ctx context.Context, id uuid.UUID) (GetMeetWithTimeCountRow, error)
	// Returns the fastest time for a specific event
	GetPersonalBestForEvent(ctx context.Context, arg GetPersonalBestForEventParams) (GetPersonalBestForEventRow, error)
	// Returns the fastest time for each event for a swimmer in a specific course type
	GetPersonalBests(ctx context.Context, arg GetPersonalBestsParams) ([]GetPersonalBestsRow, error)
	// Returns time progression for a specific event over time
	// Used for progress charts visualization
	GetProgressData(ctx context.Context, arg GetProgressDataParams) ([]GetProgressDataRow, error)
	GetRecentMeets(ctx context.Context, arg GetRecentMeetsParams) ([]GetRecentMeetsRow, error)
	GetStandard(ctx context.Context, id uuid.UUID) (TimeStandard, error)
	GetStandardTime(ctx context.Context, id uuid.UUID) (StandardTime, error)
	GetStandardTimeForEventAndAge(ctx context.Context, arg GetStandardTimeForEventAndAgeParams) (StandardTime, error)
	GetSwimmer(ctx context.Context, id uuid.UUID) (Swimmer, error)
	// In a multi-user scenario, this would filter by user_id
	// For single-user MVP, just return the first swimmer
	GetSwimmerByUserID(ctx context.Context) (Swimmer, error)
	GetTime(ctx context.Context, id uuid.UUID) (Time, error)
	GetTimeWithMeet(ctx context.Context, id uuid.UUID) (GetTimeWithMeetRow, error)
	GetTotalMeetCount(ctx context.Context, swimmerID uuid.UUID) (int32, error)
	GetTotalTimeCount(ctx context.Context, swimmerID uuid.UUID) (int32, error)
	// Check if a given time is faster than all existing times for this event/course
	IsPersonalBest(ctx context.Context, arg IsPersonalBestParams) (bool, error)
	ListMeets(ctx context.Context, arg ListMeetsParams) ([]ListMeetsRow, error)
	ListStandardTimes(ctx context.Context, standardID uuid.UUID) ([]StandardTime, error)
	ListStandards(ctx context.Context, arg ListStandardsParams) ([]TimeStandard, error)
	ListSwimmers(ctx context.Context) ([]Swimmer, error)
	ListTimes(ctx context.Context, arg ListTimesParams) ([]ListTimesRow, error)
	ListTimesByMeet(ctx context.Context, meetID uuid.UUID) ([]Time, error)
	StandardExists(ctx context.Context, id uuid.UUID) (bool, error)
	StandardNameExists(ctx context.Context, arg StandardNameExistsParams) (bool, error)
	UpdateMeet(ctx context.Context, arg UpdateMeetParams) (Meet, error)
	UpdateStandard(ctx context.Context, arg UpdateStandardParams) (TimeStandard, error)
	UpdateStandardTime(ctx context.Context, arg UpdateStandardTimeParams) (StandardTime, error)
	UpdateSwimmer(ctx context.Context, arg UpdateSwimmerParams) (Swimmer, error)
	UpdateTime(ctx context.Context, arg UpdateTimeParams) (Time, error)
	UpsertStandardTime(ctx context.Context, arg UpsertStandardTimeParams) (StandardTime, error)
}

var _ Querier = (*Queries)(nil)
