// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standard.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStandard = `-- name: CreateStandard :one
INSERT INTO time_standards (name, description, course_type, gender, is_preloaded)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, course_type, gender, is_preloaded, created_at, updated_at
`

type CreateStandardParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CourseType  string      `json:"course_type"`
	Gender      string      `json:"gender"`
	IsPreloaded bool        `json:"is_preloaded"`
}

func (q *Queries) CreateStandard(ctx context.Context, arg CreateStandardParams) (TimeStandard, error) {
	row := q.db.QueryRow(ctx, createStandard,
		arg.Name,
		arg.Description,
		arg.CourseType,
		arg.Gender,
		arg.IsPreloaded,
	)
	var i TimeStandard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CourseType,
		&i.Gender,
		&i.IsPreloaded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStandard = `-- name: DeleteStandard :exec
DELETE FROM time_standards
WHERE id = $1
`

func (q *Queries) DeleteStandard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStandard, id)
	return err
}

const getStandard = `-- name: GetStandard :one
SELECT id, name, description, course_type, gender, is_preloaded, created_at, updated_at
FROM time_standards
WHERE id = $1
`

func (q *Queries) GetStandard(ctx context.Context, id uuid.UUID) (TimeStandard, error) {
	row := q.db.QueryRow(ctx, getStandard, id)
	var i TimeStandard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CourseType,
		&i.Gender,
		&i.IsPreloaded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStandards = `-- name: ListStandards :many
SELECT id, name, description, course_type, gender, is_preloaded, created_at, updated_at
FROM time_standards
WHERE ($1::varchar = '' OR course_type = $1)
  AND ($2::varchar = '' OR gender = $2)
ORDER BY is_preloaded DESC, name ASC
`

type ListStandardsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) ListStandards(ctx context.Context, arg ListStandardsParams) ([]TimeStandard, error) {
	rows, err := q.db.Query(ctx, listStandards, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeStandard{}
	for rows.Next() {
		var i TimeStandard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CourseType,
			&i.Gender,
			&i.IsPreloaded,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const standardExists = `-- name: StandardExists :one
SELECT EXISTS(SELECT 1 FROM time_standards WHERE id = $1)
`

func (q *Queries) StandardExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, standardExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const standardNameExists = `-- name: StandardNameExists :one
SELECT EXISTS(SELECT 1 FROM time_standards WHERE name = $1 AND id != $2)
`

type StandardNameExistsParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) StandardNameExists(ctx context.Context, arg StandardNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, standardNameExists, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStandard = `-- name: UpdateStandard :one
UPDATE time_standards
SET name = $2, description = $3, course_type = $4, gender = $5
WHERE id = $1
RETURNING id, name, description, course_type, gender, is_preloaded, created_at, updated_at
`

type UpdateStandardParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CourseType  string      `json:"course_type"`
	Gender      string      `json:"gender"`
}

func (q *Queries) UpdateStandard(ctx context.Context, arg UpdateStandardParams) (TimeStandard, error) {
	row := q.db.QueryRow(ctx, updateStandard,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CourseType,
		arg.Gender,
	)
	var i TimeStandard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CourseType,
		&i.Gender,
		&i.IsPreloaded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
