// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standardtime.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStandardTime = `-- name: CreateStandardTime :one
INSERT INTO standard_times (standard_id, event, age_group, time_ms)
VALUES ($1, $2, $3, $4)
RETURNING id, standard_id, event, age_group, time_ms, created_at, updated_at
`

type CreateStandardTimeParams struct {
	StandardID uuid.UUID `json:"standard_id"`
	Event      string    `json:"event"`
	AgeGroup   string    `json:"age_group"`
	TimeMs     int32     `json:"time_ms"`
}

func (q *Queries) CreateStandardTime(ctx context.Context, arg CreateStandardTimeParams) (StandardTime, error) {
	row := q.db.QueryRow(ctx, createStandardTime,
		arg.StandardID,
		arg.Event,
		arg.AgeGroup,
		arg.TimeMs,
	)
	var i StandardTime
	err := row.Scan(
		&i.ID,
		&i.StandardID,
		&i.Event,
		&i.AgeGroup,
		&i.TimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStandardTime = `-- name: DeleteStandardTime :exec
DELETE FROM standard_times
WHERE id = $1
`

func (q *Queries) DeleteStandardTime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStandardTime, id)
	return err
}

const deleteStandardTimesByStandardID = `-- name: DeleteStandardTimesByStandardID :exec
DELETE FROM standard_times
WHERE standard_id = $1
`

func (q *Queries) DeleteStandardTimesByStandardID(ctx context.Context, standardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStandardTimesByStandardID, standardID)
	return err
}

const getStandardTime = `-- name: GetStandardTime :one
SELECT id, standard_id, event, age_group, time_ms, created_at, updated_at
FROM standard_times
WHERE id = $1
`

func (q *Queries) GetStandardTime(ctx context.Context, id uuid.UUID) (StandardTime, error) {
	row := q.db.QueryRow(ctx, getStandardTime, id)
	var i StandardTime
	err := row.Scan(
		&i.ID,
		&i.StandardID,
		&i.Event,
		&i.AgeGroup,
		&i.TimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStandardTimeForEventAndAge = `-- name: GetStandardTimeForEventAndAge :one
SELECT id, standard_id, event, age_group, time_ms, created_at, updated_at
FROM standard_times
WHERE standard_id = $1 AND event = $2 AND age_group = $3
`

type GetStandardTimeForEventAndAgeParams struct {
	StandardID uuid.UUID `json:"standard_id"`
	Event      string    `json:"event"`
	AgeGroup   string    `json:"age_group"`
}

func (q *Queries) GetStandardTimeForEventAndAge(ctx context.Context, arg GetStandardTimeForEventAndAgeParams) (StandardTime, error) {
	row := q.db.QueryRow(ctx, getStandardTimeForEventAndAge, arg.StandardID, arg.Event, arg.AgeGroup)
	var i StandardTime
	err := row.Scan(
		&i.ID,
		&i.StandardID,
		&i.Event,
		&i.AgeGroup,
		&i.TimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStandardTimes = `-- name: ListStandardTimes :many
SELECT id, standard_id, event, age_group, time_ms, created_at, updated_at
FROM standard_times
WHERE standard_id = $1
ORDER BY 
    CASE event
        WHEN '50FR' THEN 1 WHEN '100FR' THEN 2 WHEN '200FR' THEN 3 WHEN '400FR' THEN 4 WHEN '800FR' THEN 5 WHEN '1500FR' THEN 6
        WHEN '50BK' THEN 7 WHEN '100BK' THEN 8 WHEN '200BK' THEN 9
        WHEN '50BR' THEN 10 WHEN '100BR' THEN 11 WHEN '200BR' THEN 12
        WHEN '50FL' THEN 13 WHEN '100FL' THEN 14 WHEN '200FL' THEN 15
        WHEN '200IM' THEN 16 WHEN '400IM' THEN 17
        ELSE 99
    END,
    CASE age_group
        WHEN '10U' THEN 1 WHEN '11-12' THEN 2 WHEN '13-14' THEN 3 WHEN '15-17' THEN 4 WHEN 'OPEN' THEN 5
        ELSE 99
    END
`

func (q *Queries) ListStandardTimes(ctx context.Context, standardID uuid.UUID) ([]StandardTime, error) {
	rows, err := q.db.Query(ctx, listStandardTimes, standardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandardTime{}
	for rows.Next() {
		var i StandardTime
		if err := rows.Scan(
			&i.ID,
			&i.StandardID,
			&i.Event,
			&i.AgeGroup,
			&i.TimeMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandardTime = `-- name: UpdateStandardTime :one
UPDATE standard_times
SET event = $2, age_group = $3, time_ms = $4
WHERE id = $1
RETURNING id, standard_id, event, age_group, time_ms, created_at, updated_at
`

type UpdateStandardTimeParams struct {
	ID       uuid.UUID `json:"id"`
	Event    string    `json:"event"`
	AgeGroup string    `json:"age_group"`
	TimeMs   int32     `json:"time_ms"`
}

func (q *Queries) UpdateStandardTime(ctx context.Context, arg UpdateStandardTimeParams) (StandardTime, error) {
	row := q.db.QueryRow(ctx, updateStandardTime,
		arg.ID,
		arg.Event,
		arg.AgeGroup,
		arg.TimeMs,
	)
	var i StandardTime
	err := row.Scan(
		&i.ID,
		&i.StandardID,
		&i.Event,
		&i.AgeGroup,
		&i.TimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStandardTime = `-- name: UpsertStandardTime :one
INSERT INTO standard_times (standard_id, event, age_group, time_ms)
VALUES ($1, $2, $3, $4)
ON CONFLICT (standard_id, event, age_group) 
DO UPDATE SET time_ms = EXCLUDED.time_ms
RETURNING id, standard_id, event, age_group, time_ms, created_at, updated_at
`

type UpsertStandardTimeParams struct {
	StandardID uuid.UUID `json:"standard_id"`
	Event      string    `json:"event"`
	AgeGroup   string    `json:"age_group"`
	TimeMs     int32     `json:"time_ms"`
}

func (q *Queries) UpsertStandardTime(ctx context.Context, arg UpsertStandardTimeParams) (StandardTime, error) {
	row := q.db.QueryRow(ctx, upsertStandardTime,
		arg.StandardID,
		arg.Event,
		arg.AgeGroup,
		arg.TimeMs,
	)
	var i StandardTime
	err := row.Scan(
		&i.ID,
		&i.StandardID,
		&i.Event,
		&i.AgeGroup,
		&i.TimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
