// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: swimmer.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSwimmers = `-- name: CountSwimmers :one
SELECT COUNT(*) FROM swimmers
`

func (q *Queries) CountSwimmers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSwimmers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSwimmer = `-- name: CreateSwimmer :one
INSERT INTO swimmers (name, birth_date, gender)
VALUES ($1, $2, $3)
RETURNING id, name, birth_date, gender, created_at, updated_at
`

type CreateSwimmerParams struct {
	Name      string      `json:"name"`
	BirthDate pgtype.Date `json:"birth_date"`
	Gender    string      `json:"gender"`
}

func (q *Queries) CreateSwimmer(ctx context.Context, arg CreateSwimmerParams) (Swimmer, error) {
	row := q.db.QueryRow(ctx, createSwimmer, arg.Name, arg.BirthDate, arg.Gender)
	var i Swimmer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSwimmer = `-- name: DeleteSwimmer :exec
DELETE FROM swimmers
WHERE id = $1
`

func (q *Queries) DeleteSwimmer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSwimmer, id)
	return err
}

const getSwimmer = `-- name: GetSwimmer :one
SELECT id, name, birth_date, gender, created_at, updated_at
FROM swimmers
WHERE id = $1
`

func (q *Queries) GetSwimmer(ctx context.Context, id uuid.UUID) (Swimmer, error) {
	row := q.db.QueryRow(ctx, getSwimmer, id)
	var i Swimmer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSwimmerByUserID = `-- name: GetSwimmerByUserID :one
SELECT id, name, birth_date, gender, created_at, updated_at
FROM swimmers
LIMIT 1
`

// In a multi-user scenario, this would filter by user_id
// For single-user MVP, just return the first swimmer
func (q *Queries) GetSwimmerByUserID(ctx context.Context) (Swimmer, error) {
	row := q.db.QueryRow(ctx, getSwimmerByUserID)
	var i Swimmer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSwimmers = `-- name: ListSwimmers :many
SELECT id, name, birth_date, gender, created_at, updated_at
FROM swimmers
ORDER BY name
`

func (q *Queries) ListSwimmers(ctx context.Context) ([]Swimmer, error) {
	rows, err := q.db.Query(ctx, listSwimmers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Swimmer{}
	for rows.Next() {
		var i Swimmer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthDate,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSwimmer = `-- name: UpdateSwimmer :one
UPDATE swimmers
SET name = $2, birth_date = $3, gender = $4
WHERE id = $1
RETURNING id, name, birth_date, gender, created_at, updated_at
`

type UpdateSwimmerParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	BirthDate pgtype.Date `json:"birth_date"`
	Gender    string      `json:"gender"`
}

func (q *Queries) UpdateSwimmer(ctx context.Context, arg UpdateSwimmerParams) (Swimmer, error) {
	row := q.db.QueryRow(ctx, updateSwimmer,
		arg.ID,
		arg.Name,
		arg.BirthDate,
		arg.Gender,
	)
	var i Swimmer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
